### DISCUSSION TITLE
Use Emby oauth token

### DISCUSSION THREAD

**Discussion by d3mystified** [arabcoders/watchstate#520] [General] [answered]
I have an Emby server shared with me (I'm not an admin). So I cannot create an API key for it. However, oauth tokens are easily created.

Can these be supported?

**Comment by arabcoders** [comment]
Hi, sadly the way we designed the API revolves around having access to full API. 

However, it might be possible to use simple import/export without the majority of the functionality try adding this to your `/config/config/seevers.yaml`

```yaml
emby_oauth:
  type: emby
  url: 'https://emby.server'
  token: your_oauth_token
  uuid: server_uuid
  user: your_user_id
  import:
    enabled: true
    lastSync: null
  export:
    enabled: true
    lastSync: null
  webhook:
    match:
      user: true
      uuid: true
    token: not_used
  options: {}
```

replace replace what needed
