### DISCUSSION TITLE
Pls help a n00b on Synology

### DISCUSSION THREAD

**Discussion by Neobond** [arabcoders/watchstate#556] [General] [answered]
Apologies in advance for being clueless, I tried to follow the instructions on the main page. Changed the port, because qBittorrent uses 8080, and I changed the .data:/config:rw path to my local docker folder on volume1

I confirmed user id (me, not root).

Obviously somewhere I have gone wrong.

Used this in Portainer to create the Stack and ran it to create the container:
```
services:
    watchstate:
        image: ghcr.io/arabcoders/watchstate:latest
        # To change the user/group id associated with the tool change the following line.
        user: "${UID:-1026}:${GID:-100}"
        container_name: watchstate
        restart: unless-stopped
        ports:
            - "8881:8881" # The port which will serve WebUI + API + Webhooks
        volumes:
            - /volume1/docker/watchstate:/config:rw # mount current directory to container /config directory.
```
But I get ERR_CONNECTION_REFUSED on http://mynas.local:8881

Here is the Portainer log:

![20242509_161405](https://github.com/user-attachments/assets/480d4309-b152-4b05-9ade-b7baa812e839)

Docker Manager log:

![20242509_162002](https://github.com/user-attachments/assets/3853443b-6983-4474-98af-9bbf2be8052b)

I also tried to setup the container as a scheduled task using

```
docker run -d --name=watchstate \
-p 8881:8881 \
-e PUID=1026 \
-e PGID=100 \
-v /volume1/docker/watchstate:/config \
--restart always \
ghcr.io/arabcoders/watchstate
```

but it kept crashing and restarting, and giving a network error if I tried to manually stop/delete.

Appreciate any guidance!
