### DISCUSSION TITLE
Having trouble to configure mapper from plex to jellyfin

### DISCUSSION THREAD

**Discussion by NooNameR** [arabcoders/watchstate#634] [General] [answered]
Hey for some reason watchstate is picking my Display name (`Denys`) over username (`usernamex`) in plex:

```
Renaming invalid username 'Denys'. username must be in [a-z_0-9], renaming to '50d538f0'
```

So I'm not sure how that works, I was trying to create `mapper.yaml` and place it under `/config/mapper.yaml` but I do not even know what to pick for my plex username to match it with jellyfin

**Comment by arabcoders** [comment]
Hello,

Sadly, this message could mean one of two things, the display username, or the actual mapping username, sadly i didn't differentiate the message between those two, that has been fixed locally and will be in latest hopefully by the end of today.

The mapper v1 spec can be found at 

https://github.com/arabcoders/watchstate/blob/master/FAQ.md#whats-the-schema-for-the-mapperyaml-file

essentially you want

```
# 1st user...
-   my_plex_server:
        name: "mike_jones"
        options: { }
    my_jellyfin_server:
        name: "jones_mike"
        options: { }
    my_emby_server:
        name: "mikeJones"
        options: { }
```

the name field refers to whatever watchstate determine is the user name from backend, and this changes depends on backend, for example plex has many things that could be a username, but sometimes exists. once you get the mapping works, it will work regardless of the error message you see.

I am going to work on v2 of `mapper.yaml` to make it possible to pick, rename etc


once #635 is merged you will be able to control the username so you can replace it with something that is compatible

**Reply by NooNameR** [reply]
Hey, sorry for re-open:

latest version
```
[2025-04-06T09:35:04+00:00] ERROR: SYSTEM: Renaming invalid user name 'plex: Denys' to 'plex: 50d538f0'. username must be in [a-z_0-9] format.
```

/config/mapper.yaml
```
version: "1.5"
map:
-   plex:
        name: "noonamer"
        options: { }
    jellyfin:
        name: "noonamer"
        options: { }
```

Denys is my display name on plex

**Reply by arabcoders** [reply, marked as answer]
> Hey, sorry for re-open:
> 
> 
> 
> latest version
> 
> ```
> 
> [2025-04-06T09:35:04+00:00] ERROR: SYSTEM: Renaming invalid user name 'plex: Denys' to 'plex: 50d538f0'. username must be in [a-z_0-9] format.
> 
> ```
> 
> 
> 
> /config/mapper.yaml
> 
> ```
> 
> version: "1.5"
> 
> map:
> 
> -   plex:
> 
>         name: "noonamer"
> 
>         options: { }
> 
>     jellyfin:
> 
>         name: "noonamer"
> 
>         options: { }
> 
> ```
> 
> 
> 
> Denys is my display name on plex

Hi, you should use whatever name server send us in your case its `Denys` if you want to change it locally please use `replace_with: "noonamer"` plex is really annoying with how they report the name differently depending on which endpoint you call. 

```yaml
version: "1.5"
map:
-   plex:
        name: "Denys"
        replace_with: "noonamer"
    jellyfin:
        name: "noonamer"
        options: { }
```

i will have another update to fix related bug where the mapper doesn't really function if there is no replace_with key
