### ISSUE TITLE
Consider building the container to run as non-root

### ISSUE THREAD

**Issue by onedr0p** [ArabCoders/watchstate#213]
Hi 👋🏼 

I've been working with containers for a long time. Rootful containers are considered bad practice and are also a major security concern. I don't see why this container would need to run as root, you could instead document this setup:

1. Create the volume on your host and correctly set the permissions.

    ```sh
    mkdir watchstate-config
    chown -R <UID>:<GID> watchstate-config
    ```

2. Run the container as a user other than the default user in the container:

    ```sh
    docker run --user <UID>:<GID> -v $(PWD)/watchstate-config:/config ... ghcr.io/arabcoders/watchstate:v1.0.0
    ```

This would require you to update the container build to not run as root by default as well.

Thanks for listening!

**Comment by onedr0p** [comment]
You could also point users to this project to help run the service as a cron, instead of baking it into the container:

https://github.com/mcuadros/ofelia

**Comment by ArabCoders** [comment]
Hi

Thank you for your concerns. The container and the tool does not need to run as root there are already checks to prevent running the tool from running as user 0. When you run the console command it executes it under `user` not root. What is missing is the actual change user step in Dockerfile. and i am planning to shuffle some of the things baked in entrypoint to the dockerfile. after that it should be easy to activate the user directive. 

About the the external runtimes, everything that is external to the tool itself can be disabled including http, cron, redis. I include everything needed for ease of management for users. However you are free to disable everything included and use you own scheduler, frontend proxy or redis cache alternative. 

Thank you

**Comment by ArabCoders** [comment]
@onedr0p `ghcr.io/arabcoders/watchstate:dev` is now rootless, could you pull and try it now?

**Comment by onedr0p** [comment]
I didn't run the container but I reviewed your changes, there's a couple more things I would do.

- Keep the running processes in the container to 1
- Remove redis and make that an external dep
- Remove the cron logic and make that also a external dep.

Here's quick example I whipped up

```yaml
version: "3"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes: 
      - /hostpath/watchstate/cache:/data

  watchstate:
    image: ghcr.io/arabcoders/watchstate
    depends_on:
      - redis
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.watchstate.schedule: "@hourly"
      ofelia.job-exec.watchstate.command: "/usr/bin/console system:tasks --run --save-log"
```

More importantly, does watchstate need to run continuously? Does it need a webserver? Couldn't the entrypoint to the container be ..

```dockerfile
ENTRYPOINT ["/usr/bin/console"]
CMD ["system:tasks", "--run", "--save-log" ]
```

I know these aren't root related but I am just trying to help you build the docker part more eloquently.
