### ISSUE TITLE
[BUG] Not importing all items from Plex

### ISSUE THREAD

**Issue by stokkes** [ArabCoders/watchstate#284]
**Describe the bug**

syncing Plex > Jellyfin. 

For some reason, Watchstate isn't detecting all shows/épisodes/movies in my Plex library. 

I noticed this because in Jellyfin I had a bunch of shows that didn't have all episodes marked as watched. 

When I looked at the backend for Plex using `backend:search:query` the episodes just aren't there, but they ARE watched in Plex.  It's very inconsistent. Like the same show may have some episodes of a season marked as watched and others not when they are all watched in Plex. 

I also notice the Plex import only makes 73 calls to the backend but I have about 1400 shows and 15000+ episodes. There aren't any errors running with `-vvv` other than some external IDs that can't be found (which is normal for some of the obscure shows I have). 

**To Reproduce**
Not sure 🤔 

**Expected behavior**
All shows and episodes would appear in the watchstate database. 

** Tool Version:**
WatchState 068d935

**Comment by ArabCoders** [comment]
Hello,

Thanks for your report, if everything is syncing except for episodes or shows this likely means there is no common GUIDs between the shows.

to determine the cause, do something like this

```bash
$ docker exec -ti watchstate console db:list --title "ShowName" --output yaml
```
check the GUIDs, and make sure both plex and jellyfin has the same id

you can see the raw responses related to the shows using the following command

```bash
$ docker exec -ti watchstate console backend:search:query backend_name "ShowName" --output yaml --include-raw-response  --limit 1
```

do it for both servers and post the results if you are unable to determine the problem make sure to mask any identifiable information. This likely related to series not having a GUID in common.

**Comment by ArabCoders** [comment]
@stokkes any updates?

**Comment by ArabCoders** [comment]
Closing as there is no reply for week. Please reopen if you feel the issue is present.

**Comment by stokkes** [comment]
Hi @ArabCoders .. sorry for not responding, my notifications from Github were apparently not getting to me.

Before I get into the Syncing, I just want to try to understand why WatchState doesn't pick up all the episodes from Plex.. If I understand properly, just doing a `watchstate console state:import`  should import all play states from my backend (in this case, it's `plex_prod`) and store it in the database, no? Again, forget the syncing, just issuing that command to my understanding queries Plex and should pull the watchstate from the entire DB.

If i take a show, The Walking Dead for example, if I run`watchstate console backend:search:query plex_prod "The Walking Dead"`, the output returns the show (good), but only returns 19 episodes in the backend (and random episodes at that), but I have all the Walking Dead Episodes and I've watched about 5 seasons.

The other weird thing I've noticed (mentioning it because maybe it's related?) is that my Plex ID for my admin user is showing up at 1 when issuing a `watchstate console backend:users:list plex_prod` (which I'm guessing is normal since I'm the admin), but when I watch episodes and setup the watchstate webhook, Plex sends a completely different ID (8610) for my exact user (I only have 1 plex account).  Here is that output:

```
[2022-12-18T15:02:38.734981-05:00] webhook.ERROR: token is valid, User matching failed. {"request":{"id":"b86ff9d3-a894-4c60-9cfe-a3671c0e8897","ip":"172.18.0.2","agent":"PlexMediaServer/1.29.2.6364-6d72b0cf6","uri":"/?apikey=api_key_removed"},"messages":["Request user id [8610] does not match configured value [1]"],"attributes":{"backend":{"id":"c55174ac499a384885f850381110546528fd2538","name":"stewie Cloud","client":"PlexMediaServer","version":"1.29.2.6364-6d72b0cf6"},"user":{"id":8610,"name":"Stokkes"},"item":{"id":"14904","type":"episode"},"webhook":{"event":"media.resume"}}} []
```

Don't want to confuse the issues, so if you think the webhook mismatch UserID isn't related to my first issue, then I can open a new github issue on that one.

**Comment by ArabCoders** [comment]
Hi, Indeed the webhook error isn't related, this is likely due to plex screwing up with their internal ids. you can safely turn off matching user if you are the only plex user using that account. Otherwise manually change the user id to the one being reported.

For the show, try running `console db:list --title "The Walking Dead" --limit 200 --output yaml` do you see all your entries or not, the command you used `watchstate console backend:search:query plex_prod "The Walking Dead"` reports what plex is matching not what is inside the database.

**Comment by stokkes** [comment]
Ok, so yes they do appear there with this command `console db:list --title "The Walking Dead" --limit 5000 --output yaml | grep "The Walking Dead - S0" | wc -l` reports back over 200 episodes, so seems good, back to sync issue.

Ok, so looks to be a GUID issue then? I found a show in particular, NCIS which has a bunch of seasons marked as unplayed in Jellyfin.. For testing, I went into Plex and marked one of the seasons as unplayed and marked it as played again (manuallly).. I then ran a `state:import` and it found the episodes! I retried with another season, same thing. So it appears that manually marking a season/episode/show/etc as unplayed and then played makes it get picked up.

I wonder if this is due to when the episode was initially played (e.g.: NCIS Season 5 was like 10+ years ago), maybe it registered a different GUID?

If this is the case, is there anyway you know of that I can force this process? I've been running Plex since it was OSXBMC so my library is very old so having to dig through tens of thousands of shows and re-marked them as watched so I can sync them to jellyfin makes me want to poke my eyes out with a dull spoon. :)

**Comment by ArabCoders** [comment]
> If this is the case, is there anyway you know of that I can force this process? I've been running Plex since it was OSXBMC so my library is very old so having to dig through tens of thousands of shows and re-marked them as watched so I can sync them to jellyfin makes me want to poke my eyes out with a dull spoon. :)

you can use `-f` from `console help state:import` `  -f, --force-full                         Force full import. Ignore last sync date.` =)

try it and report back, and you can always just delete the db and start fresh

**Comment by stokkes** [comment]
So something is very odd.. I took another show, NCIS and did the output yaml command from above.. One particular episode which is definitely marked as watched in Plex (S12E01) is not being picked up as watched by WatchState.

Here is the yaml for this one, you can see "watched" = "0", but I'm staring at my Plex screen now and it's showing as watched.. (if I manually mark as unwatched and then re-mark as watched, the 0 below turns into a 1):

```yaml
  id: 70110
  type: episode
  updated: 2021-12-15T04:04:17-05:00
  watched: false  
  via: plex_prod
  title: NCIS
  year: 2014
  season: 12
  episode: 1
  parent:
    guid_imdb: tt0364845
    guid_tmdb: '4614'
    guid_tvdb: '72108'
    guid_tvrage: '4628'
  guids: {  }
  metadata:
    jellyfin_dev: 
      id: 3a54f58131995b91cfeee5534ad4a905
      type: episode
      watched: '0'
      via: jellyfin_dev  
      title: NCIS
      guids:
        guid_imdb: tt3607318
        guid_tvdb: '4956078'
        guid_tvrage: '1065523346'
      added_at: '1639559057'
     extra:
        title: 'Twenty Klicks'
        date: '2014-09-22'
      library: 767bffe4f11c93ef34b805451a696a4e
      show: 9e78dba3a9285832eb0348e61fb8baa1
      season: '12'
      episode: '1'
      parent:
        guid_imdb: tt0364845
        guid_tmdb: '4614'
        guid_tvdb: '72108'
        guid_tvrage: '4628'
      year: '2014'
      path: '/mnt/media/tvshows/NCIS/Season 12/NCIS - S12E01 - Twenty Klicks (Bluray-1080p).mkv'
    plex_prod:
      id: '288646'
      type: episode
      watched: '0'
      via: plex_prod
      title: NCIS
      guids:
        guid_imdb: tt3607318
        guid_tmdb: '1010118'
        guid_tvdb: '4956078'
      added_at: '1655741519'
      extra:
        title: 'Twenty Klicks'
        date: '2014-09-23'
      library: '1'
      show: '7556'
      season: '12'
      episode: '1'
      parent:
       guid_imdb: tt0364845
        guid_tmdb: '4614'
        guid_tvdb: '72108'
      year: '2014'
      path: '/mnt/media/tvshows/NCIS/Season 12/NCIS - S12E01 - Twenty Klicks (Bluray-1080p).mkv'
  extra:
    jellyfin_dev:
      event: task.import
      received_at: '2022-11-18T04:58:50-05:00'
    plex_prod:
      event: task.import
      received_at: '2022-12-18T19:06:13-05:00'
```

**Comment by ArabCoders** [comment]
If you do manual sync does the status get updated? if bot with the -f flag does that correct the problem?

Unfortunately it quite late where i am, it seems to me the problem is that jellyfin has newer date on media thus taking priority over plex. Before adding the 2nd backend in the import process you should added it as metadata source only. After syncing your watch state to jellyfin you then turn on full import from jellyfin.

**Comment by stokkes** [comment]
Ha! You were definitely onto something.

Looks like WatchState did prioritize Jellyfin (not sure why?). I nuked the entire config and restarted from scratch. Added the Plex backend only and then an import. It imported all episodes.. Oddly enough, with this new config, it imported ALL the episodes, with the previous import, no matter if I forced it, it would only import about 1/5th of the episodes I have.

And... the episodes are marked as watched when I do the yaml output.

Not sure if with this information you can prevent this from happening. I'm not sure how to recreate the mess I got myself in, but it almost seems as though because I had watched a lot of these episodes years ago and then maybe configured Jellyfin first before doing an import Plex, that it somehow sees that the episodes not being watched in Jellyfin with a newer timestamp than the old Plex one means it won't mark it as watched.

Appreciate the help! You can keep this closed, hopefully if someone has a similar issue they come across this.

**Comment by stokkes** [comment]
Ok spoke a bit too soon. Watch state for that NCIS episode now works (as well as other ones).. I then added Jellyfin and enabled the export on that backend. Doing a `state:export -f` doesn't seem to update the watch state. Here is the yaml output (notice the plex is now watched, the GUIDs match, but Jellyfin is still showing watched as 0)..

```yaml
  id: 70061
  type: episode
  updated: 2017-12-26T16:09:43-05:00
  watched: true
  via: plex
  title: NCIS
  year: 2014
  season: 12
  episode: 1
  parent:
    guid_imdb: tt0364845
    guid_tmdb: '4614'
    guid_tvdb: '72108'
  guids: {  }
  metadata:
    jellyfin:
      id: 3a54f58131995b91cfeee5534ad4a905
      type: episode
      watched: '0'
      via: jellyfin
      title: NCIS
      guids:
        guid_imdb: tt3607318
        guid_tvdb: '4956078'
        guid_tvrage: '1065523346'
      added_at: '1639559057'
      extra:
        title: 'Twenty Klicks'
        date: '2014-09-22'
      library: 767bffe4f11c93ef34b805451a696a4e
      show: 9e78dba3a9285832eb0348e61fb8baa1
      season: '12'
     episode: '1'
      parent:
        guid_imdb: tt0364845
        guid_tmdb: '4614'
        guid_tvdb: '72108'
        guid_tvrage: '4628'
      year: '2014'
      path: '/mnt/media/tvshows/NCIS/Season 12/NCIS - S12E01 - Twenty Klicks (Bluray-1080p).mkv'
    plex:
      id: '288646'
      type: episode
      watched: '1'
      via: plex
      title: NCIS
      guids:
        guid_imdb: tt3607318
        guid_tmdb: '1010118'
        guid_tvdb: '4956078'
      added_at: '1655741519'
      extra:
        title: 'Twenty Klicks'
        date: '2014-09-23'
      library: '1'
      show: '7556'
      season: '12'
      episode: '1'
      parent:
        guid_imdb: tt0364845
        guid_tmdb: '4614'
        guid_tvdb: '72108'
      year: '2014'
      path: '/mnt/media/tvshows/NCIS/Season 12/NCIS - S12E01 - Twenty Klicks (Bluray-1080p).mkv'
      played_at: '1514322583' 
  extra:
    jellyfin:
      event: task.import
      received_at: '2022-12-18T20:30:54-05:00'
    plex:
      event: task.import
      received_at: '2022-12-18T19:51:45-05:00'
```
