### ISSUE TITLE
Other users updating synced user

### ISSUE THREAD

**Issue by ikolsteren** [ArabCoders/watchstate#49]
Users that are not the user that is setup are having their play status' updated on the user setup for sync
User X is setup on two plex servers and for both the match user and uuid set for true
snippet from servers.yaml file
```
  user: 375432
  import:
    enabled: true
    lastSync: 1650036504
  export:
    enabled: true
    lastSync: 1650036644
  webhook:
    import: true
    push: true
    match:
      user: true
      uuid: true
    token: *********************************
  persist: {  }
```
When users Y or Z watch something and its completed user X watch status sets that they have watched the same episode
