### ISSUE TITLE
Proxying via Traefik

### ISSUE THREAD

**Issue by astronyu** [arabcoders/watchstate#622]
I installed this on docker with this compose file

```yaml
services:
  watchstate:
    image: ghcr.io/arabcoders/watchstate:latest
    # To change the user/group id associated with the tool change the following line.
    user: "${UID:-1001}:${GID:-1001}"
    container_name: watchstate
    restart: unless-stopped
    ports:
      - "8089:8080" # The port which will serve WebUI + API + Webhooks
    volumes:
      - ./data:/config:rw # mount current directory to container /config directory.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.watchstate.rule=Host(my.subdomain.com)"
      - "traefik.http.routers.watchstate.entrypoints=websecure"
      - "traefik.http.routers.watchstate.tls=true"
      - "traefik.http.routers.watchstate.tls.certresolver=letsencrypt"
      - "traefik.http.services.watchstate.loadbalancer.server.port=8089"
    networks:
      - watchstate
      - frontend

networks:
  frontend:
    name: frontend
  watchstate:
    name: watchstate
```

Chowned the data folder to 1001 and I got it to run. However, when I go to my.subdomain.com, it just shows "bad gateway". I can't open ip:8089 as I did not open the port and intending to use traefik for that. Traefik shows all good and have https enabled for the subdomain.

What might be the problem if someone can help me.

Thanks.
